server:
  port: 0

spring:
  application:
    name: front-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false
      registerWithEureka: false
